/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DialogueLine = IDL.Record({
  'text' : IDL.Text,
  'speaker' : IDL.Text,
});
export const VocabularyEntry = IDL.Record({
  'word' : IDL.Text,
  'definition' : IDL.Text,
});
export const Lesson = IDL.Record({
  'title' : IDL.Text,
  'grammarTips' : IDL.Text,
  'difficulty' : IDL.Text,
  'dialogue' : IDL.Vec(DialogueLine),
  'category' : IDL.Text,
  'vocabulary' : IDL.Vec(VocabularyEntry),
});
export const QuizOption = IDL.Record({
  'text' : IDL.Text,
  'isCorrect' : IDL.Bool,
});
export const QuizQuestion = IDL.Record({
  'questionText' : IDL.Text,
  'options' : IDL.Vec(QuizOption),
});
export const LessonQuiz = IDL.Record({
  'lessonId' : IDL.Nat,
  'questions' : IDL.Vec(QuizQuestion),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'wordsLearned' : IDL.Vec(IDL.Text),
  'quizScores' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'lastActiveDay' : Time,
  'name' : IDL.Text,
  'streakDays' : IDL.Nat,
  'completedLessons' : IDL.Vec(IDL.Nat),
});
export const UserProgress = IDL.Record({
  'wordsLearned' : IDL.Vec(IDL.Text),
  'quizScores' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'lastActiveDay' : Time,
  'streakDays' : IDL.Nat,
  'completedLessons' : IDL.Vec(IDL.Nat),
});
export const QuizSubmission = IDL.Record({
  'lessonId' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLesson' : IDL.Func([Lesson], [IDL.Nat], []),
  'addQuiz' : IDL.Func([LessonQuiz], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAccount' : IDL.Func([], [], []),
  'getAllAvailableVocabularyByDifficulty' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedLessonIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getLesson' : IDL.Func([IDL.Nat], [IDL.Opt(Lesson)], ['query']),
  'getQuiz' : IDL.Func([IDL.Nat], [IDL.Opt(LessonQuiz)], ['query']),
  'getQuizScore' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
  'getVocabularyByLesson' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loadSampleData' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuiz' : IDL.Func([QuizSubmission], [IDL.Nat], []),
  'updateUserProgress' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DialogueLine = IDL.Record({ 'text' : IDL.Text, 'speaker' : IDL.Text });
  const VocabularyEntry = IDL.Record({
    'word' : IDL.Text,
    'definition' : IDL.Text,
  });
  const Lesson = IDL.Record({
    'title' : IDL.Text,
    'grammarTips' : IDL.Text,
    'difficulty' : IDL.Text,
    'dialogue' : IDL.Vec(DialogueLine),
    'category' : IDL.Text,
    'vocabulary' : IDL.Vec(VocabularyEntry),
  });
  const QuizOption = IDL.Record({ 'text' : IDL.Text, 'isCorrect' : IDL.Bool });
  const QuizQuestion = IDL.Record({
    'questionText' : IDL.Text,
    'options' : IDL.Vec(QuizOption),
  });
  const LessonQuiz = IDL.Record({
    'lessonId' : IDL.Nat,
    'questions' : IDL.Vec(QuizQuestion),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'wordsLearned' : IDL.Vec(IDL.Text),
    'quizScores' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'lastActiveDay' : Time,
    'name' : IDL.Text,
    'streakDays' : IDL.Nat,
    'completedLessons' : IDL.Vec(IDL.Nat),
  });
  const UserProgress = IDL.Record({
    'wordsLearned' : IDL.Vec(IDL.Text),
    'quizScores' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'lastActiveDay' : Time,
    'streakDays' : IDL.Nat,
    'completedLessons' : IDL.Vec(IDL.Nat),
  });
  const QuizSubmission = IDL.Record({
    'lessonId' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLesson' : IDL.Func([Lesson], [IDL.Nat], []),
    'addQuiz' : IDL.Func([LessonQuiz], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAccount' : IDL.Func([], [], []),
    'getAllAvailableVocabularyByDifficulty' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedLessonIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getLesson' : IDL.Func([IDL.Nat], [IDL.Opt(Lesson)], ['query']),
    'getQuiz' : IDL.Func([IDL.Nat], [IDL.Opt(LessonQuiz)], ['query']),
    'getQuizScore' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
    'getVocabularyByLesson' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loadSampleData' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuiz' : IDL.Func([QuizSubmission], [IDL.Nat], []),
    'updateUserProgress' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };