/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DialogueLine { 'text' : string, 'speaker' : string }
export interface Lesson {
  'title' : string,
  'grammarTips' : string,
  'difficulty' : string,
  'dialogue' : Array<DialogueLine>,
  'category' : string,
  'vocabulary' : Array<VocabularyEntry>,
}
export interface LessonQuiz {
  'lessonId' : bigint,
  'questions' : Array<QuizQuestion>,
}
export interface QuizOption { 'text' : string, 'isCorrect' : boolean }
export interface QuizQuestion {
  'questionText' : string,
  'options' : Array<QuizOption>,
}
export interface QuizSubmission {
  'lessonId' : bigint,
  'answers' : Array<bigint>,
}
export type Time = bigint;
export interface UserProfile {
  'wordsLearned' : Array<string>,
  'quizScores' : Array<[bigint, bigint]>,
  'lastActiveDay' : Time,
  'name' : string,
  'streakDays' : bigint,
  'completedLessons' : Array<bigint>,
}
export interface UserProgress {
  'wordsLearned' : Array<string>,
  'quizScores' : Array<[bigint, bigint]>,
  'lastActiveDay' : Time,
  'streakDays' : bigint,
  'completedLessons' : Array<bigint>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VocabularyEntry { 'word' : string, 'definition' : string }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLesson' : ActorMethod<[Lesson], bigint>,
  'addQuiz' : ActorMethod<[LessonQuiz], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAccount' : ActorMethod<[], undefined>,
  'getAllAvailableVocabularyByDifficulty' : ActorMethod<[], Array<string>>,
  'getAllLessons' : ActorMethod<[], Array<Lesson>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedLessonIds' : ActorMethod<[], Array<bigint>>,
  'getLesson' : ActorMethod<[bigint], [] | [Lesson]>,
  'getQuiz' : ActorMethod<[bigint], [] | [LessonQuiz]>,
  'getQuizScore' : ActorMethod<[bigint], [] | [bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProgress' : ActorMethod<[], UserProgress>,
  'getVocabularyByLesson' : ActorMethod<[bigint], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loadSampleData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuiz' : ActorMethod<[QuizSubmission], bigint>,
  'updateUserProgress' : ActorMethod<[bigint, Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];